version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db_app
    environment:
      - POSTGRES_DB=FA_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    env_file:
#      - .env
  app:
    build: .
    container_name: fastapi_blog
    command: ["/app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
